import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

// OpenAI key lives only in the RLS-locked app_config table (service role reads
// it). Never in the repo or client.
let cachedKey: string | null = null;
async function getOpenAIKey(): Promise<string> {
  if (cachedKey) return cachedKey;
  const url = Deno.env.get("SUPABASE_URL");
  const svc = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !svc) throw new Error("missing service env");
  const r = await fetch(
    `${url}/rest/v1/app_config?key=eq.openai_key&select=val`,
    { headers: { apikey: svc, Authorization: `Bearer ${svc}` } },
  );
  if (!r.ok) throw new Error("config fetch failed");
  const rows = await r.json();
  const k = rows?.[0]?.val;
  if (!k) throw new Error("key not configured");
  cachedKey = k;
  return k;
}

// Generate-on-demand cache (public.explanation_cache). Each unique content key
// is generated by the LLM at most once PER LOCALE, ever; everyone after reads
// the cache. English keys stay unprefixed (back-compat with rows + old
// clients); other locales are scoped `<lang>:<key>` so an English answer can
// never shadow a Tamil one.
async function cacheGet(key: string): Promise<string | null> {
  const url = Deno.env.get("SUPABASE_URL");
  const svc = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !svc) return null;
  try {
    const r = await fetch(
      `${url}/rest/v1/explanation_cache?key=eq.${encodeURIComponent(key)}&select=explanation`,
      { headers: { apikey: svc, Authorization: `Bearer ${svc}` } },
    );
    if (!r.ok) return null;
    const rows = await r.json();
    return rows?.[0]?.explanation ?? null;
  } catch (_) {
    return null;
  }
}
async function cachePut(key: string, explanation: string): Promise<void> {
  const url = Deno.env.get("SUPABASE_URL");
  const svc = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !svc) return;
  try {
    await fetch(`${url}/rest/v1/explanation_cache`, {
      method: "POST",
      headers: {
        apikey: svc,
        Authorization: `Bearer ${svc}`,
        "Content-Type": "application/json",
        Prefer: "resolution=merge-duplicates,return=minimal",
      },
      body: JSON.stringify({ key, explanation }),
    });
  } catch (_) { /* best-effort */ }
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, "Content-Type": "application/json" },
  });
}

// House style for Tamil (matches the bundled explanations_ta pass): simple,
// natural Tamil in Tamil script; grammar terms (noun, verb, plural...) and all
// quoted English learning material stay in ENGLISH.
const SYS_EN =
  "You are Ratel, a warm, concise English tutor (a fearless honey badger). In 1-2 short sentences (max 40 words), teach WHY the correct answer is right and what the learner's answer actually is or why it does not fit. Encouraging, plain language, never harsh. Plain text only.";
const SYS_TA =
  "You are Ratel, a warm, concise English tutor (a fearless honey badger) helping a Tamil speaker learn English. In 1-2 short sentences (max 40 words), teach WHY the correct answer is right and what the learner's answer actually is or why it does not fit. Write in simple, natural Tamil (Tamil script), but keep English grammar terms (noun, verb, plural, subject...) and every quoted English word or answer in English exactly as given. Encouraging, never harsh. Plain text only.";

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  try {
    const { key, prompt, userAnswer, correctAnswer, locale } = await req.json();
    if (!prompt || !correctAnswer) return json({ error: "missing_fields" }, 400);

    const lang = locale === "ta" ? "ta" : "en";
    const ck = (typeof key === "string" && key.length > 0)
      ? (lang === "en" ? key : `${lang}:${key}`)
      : null;

    // 1) Cache hit -> no LLM call.
    if (ck) {
      const cached = await cacheGet(ck);
      if (cached) return json({ explanation: cached, cached: true });
    }

    // 2) Generate once per (key, locale).
    const apiKey = await getOpenAIKey();
    const user =
      `Question: ${prompt}\nLearner answered: ${userAnswer ?? "(left blank)"}\nCorrect answer: ${correctAnswer}\nGive the brief explanation.`;
    const ai = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: lang === "ta" ? SYS_TA : SYS_EN },
          { role: "user", content: user },
        ],
        max_tokens: 120,
        temperature: 0.5,
      }),
    });
    if (!ai.ok) {
      const t = await ai.text();
      return json({ error: "llm_error", detail: t.slice(0, 160) }, 502);
    }
    const data = await ai.json();
    const explanation = (data.choices?.[0]?.message?.content ?? "").trim() ||
      "Take another look — the correct answer is shown above.";

    // 3) Cache for next time.
    if (ck) await cachePut(ck, explanation);
    return json({ explanation });
  } catch (e) {
    return json({ error: "bad_request", detail: String(e).slice(0, 160) }, 400);
  }
});
